### ISSUE TITLE
signup.phpのpostの処理部分について

### ISSUE THREAD

**Issue by ir77** [dit-rohm/textbook#101]
[signup.md](https://github.com/dit-rohm/textbook/blob/master/autumn/signup/signup.md)の`2. データを受け取る部分（PHP）`における以下の処理は

> ``` php
> if ((isset($_POST['user_name']) || $_POST['user_name'] !== '') && ...
> ```

次のように&&で判定するべき部分だと思ったんですが、、、

> ``` php
> if ((isset($_POST['user_name']) && $_POST['user_name'] !== '') && ...
> ```

なぜ||で判定されているのでしょうか。

**Comment by mikoim** [comment]
確かに．
$_POST['HOGE']が未定義でも比較するという暴挙に…

`Notice: Undefined index: user_name in FOOBAR on line N`
