### ISSUE TITLE
教科書のテンプレ的なのほしい

### ISSUE THREAD

**Issue by nakanishy** [dit-rohm/textbook#50]
毎回書き方がバラバラなので、統一した書き方にしたい。
例えば、以下の様なフォーマットを定めて、毎回それにしたがって教科書を作成する

・要求仕様（完成画像と動作の説明）
・作成手順（まず画像をおいて、jsで動作をつける...）
・今回使う構文や関数（getElementByIdやif, forなど）

**Comment by ir77** [comment]
完成画像や動作を置いてから作成手順が始まるのは分かりやすそうですね。

**Comment by mikoim** [comment]
「教科書のテンプレ的なのほしい」
とはなんだったのか（´・ω・） …

**Comment by ir77** [comment]
次回勉強会班のアジェンダに追加するわ。

**Comment by ir77** [comment]
https://github.com/dit-rohm/textbook/wiki/Template
@Tomoki-K 
テンプレート作成忘れぬようおなしゃす。

**Comment by mikoim** [comment]
@Tomoki-K
ASAPでお願いしま（´・ω・） ｽ

**Comment by cure-tmk** [comment]
了解しました。
