### ISSUE TITLE
秋学期勉強会のディレクトリ名

### ISSUE THREAD

**Issue by tomoyat1** [dit-rohm/textbook#76]
1. 11..20
2. 1a...10a、及びこれに類する命名規則

**Comment by mikoim** [comment]
とりあえず，/にspring, autumnでも作って分けた方が良いんじゃないかとおもた（´・ω・） ｽ

**Comment by Tamrin007** [comment]
あと1じゃなくて01にしませう

**Comment by mikoim** [comment]
GitHubのソートがもう少し賢かったら良いん（´・ω・） ｽｹﾄﾞ…

**Comment by mikoim** [comment]
このissueもう終わってるやん（´・ω・） ｽ
