### ISSUE TITLE
テキスト内のコードのエラーチェック

### ISSUE THREAD

**Issue by mikoim** [dit-rohm/textbook#95]
授業内でミスを指摘されるのはアレゲ．
どうにかしてテキスト内のコードのsyntax errorの検出を自動化したい．
テキストとコードが分離されていれば，容易に実現できそうなんですけどねぇ…
- codeブロックからぶっこぬいて言語判定 からの エラーチェック？
- lstinputlisting的な何かに対応したテキストビューワーを作る？

御意見求む．
→ **人間の目でチェック**するというのは無しで．

**Comment by ir77** [comment]
いきなり人間の目でチェックする話をしてしまって申し訳ないんだけども、毎回レビュワーが決まってないからレビューが全体的におろそかになっている面はあるかも。

**Comment by mikoim** [comment]
確かに．
少なくとも「実際に通してみれば」防げるわけですからね…
これまでの一回生による人力エラーチェックは有効．

---

レビュー以前に，PRを作成した段階でエラーを検出したいというのが#95
